/* mask-identity fuzz: the client's lfn_leaf2fcb MUST produce byte-identical
 * 11-byte FCB templates to the server's lfn_mask2fcb for every mask. */
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#define upchar(c) ((char)toupper((unsigned char)(c)))
#include "maskcmp_srv.c" /* generated by run.sh from fs.c+ethersrv.c */
#include "maskcmp_gen.c"
static long fails = 0, total = 0;
static void chk(const char *m) {
  char s[12]; unsigned char c[12];
  memset(s, 'x', 12); memset(c, 'x', 12);
  lfn_mask2fcb(s, m);
  lfn_leaf2fcb(c, (unsigned char *)m);
  total++;
  if (memcmp(s, c, 11) != 0) {
    if (fails < 20)
      printf("  DIVERGE '%s': srv='%.11s' cli='%.11s'\n", m, s, (char *)c);
    fails++;
  }
}
int main(void) {
  static const char *fixed[] = {"*", "*.*", "FOO*", "FOO.B*", "FOO", ".", "..",
    "FO*BAR", "*.T", "*.c.bak", "A.B.C", "..foo", "a.b.c.d", "LONGNAME1.EXT",
    "*.", ".*", "**", "*?*.?*", "????????.???", "file_id.diz", 0};
  const char cs[] = "AZ.*?_9";
  int i, a, b, c, d, e;
  char m[8];
  for (i = 0; fixed[i]; i++) chk(fixed[i]);
  for (a = 0; a < 7; a++) for (b = 0; b < 7; b++) for (c = 0; c < 7; c++) {
    m[0]=cs[a]; m[1]=cs[b]; m[2]=cs[c]; m[3]=0; chk(m);
    for (d = 0; d < 7; d++) for (e = 0; e < 7; e++) {
      m[3]=cs[d]; m[4]=cs[e]; m[5]=0; chk(m);
    }
  }
  printf("mask identity: %ld masks, %ld divergences -> %s\n",
         total, fails, fails ? "FAIL" : "OK");
  return fails ? 1 : 0;
}
